version: '3.8'
services:
  server:
    build: ./server
    ports:
      - "4000:4000"
    env_file:
      - ./server/.env
    networks:
      - app-network

  client:
    build: ./client
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge